/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRoleRouteImport } from './routes/create-role'
import { Route as CreateClientRouteImport } from './routes/create-client'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientCreateUserRouteImport } from './routes/client.create-user'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoleRoute = CreateRoleRouteImport.update({
  id: '/create-role',
  path: '/create-role',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateClientRoute = CreateClientRouteImport.update({
  id: '/create-client',
  path: '/create-client',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientCreateUserRoute = ClientCreateUserRouteImport.update({
  id: '/client/create-user',
  path: '/client/create-user',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/create-client': typeof CreateClientRoute
  '/create-role': typeof CreateRoleRoute
  '/dashboard': typeof DashboardRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sign-in': typeof SignInRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/users': typeof UsersRoute
  '/client/create-user': typeof ClientCreateUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/create-client': typeof CreateClientRoute
  '/create-role': typeof CreateRoleRoute
  '/dashboard': typeof DashboardRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sign-in': typeof SignInRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/users': typeof UsersRoute
  '/client/create-user': typeof ClientCreateUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/create-client': typeof CreateClientRoute
  '/create-role': typeof CreateRoleRoute
  '/dashboard': typeof DashboardRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sign-in': typeof SignInRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/users': typeof UsersRoute
  '/client/create-user': typeof ClientCreateUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/create-client'
    | '/create-role'
    | '/dashboard'
    | '/privacy-policy'
    | '/sign-in'
    | '/terms-of-use'
    | '/users'
    | '/client/create-user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/create-client'
    | '/create-role'
    | '/dashboard'
    | '/privacy-policy'
    | '/sign-in'
    | '/terms-of-use'
    | '/users'
    | '/client/create-user'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/create-client'
    | '/create-role'
    | '/dashboard'
    | '/privacy-policy'
    | '/sign-in'
    | '/terms-of-use'
    | '/users'
    | '/client/create-user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  CreateClientRoute: typeof CreateClientRoute
  CreateRoleRoute: typeof CreateRoleRoute
  DashboardRoute: typeof DashboardRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SignInRoute: typeof SignInRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  UsersRoute: typeof UsersRoute
  ClientCreateUserRoute: typeof ClientCreateUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-role': {
      id: '/create-role'
      path: '/create-role'
      fullPath: '/create-role'
      preLoaderRoute: typeof CreateRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-client': {
      id: '/create-client'
      path: '/create-client'
      fullPath: '/create-client'
      preLoaderRoute: typeof CreateClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/create-user': {
      id: '/client/create-user'
      path: '/client/create-user'
      fullPath: '/client/create-user'
      preLoaderRoute: typeof ClientCreateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  CreateClientRoute: CreateClientRoute,
  CreateRoleRoute: CreateRoleRoute,
  DashboardRoute: DashboardRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SignInRoute: SignInRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  UsersRoute: UsersRoute,
  ClientCreateUserRoute: ClientCreateUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
